function [ includes ] = get_strategy_learner_includes()
%GET_STRATEGY_LEARNER_INCLUDES Get an array with the strategy learner
%includes.
includes =[' -I/home/robocup/svn/trunk/src/Turtle2/', ...
           ' -I/home/robocup/svn/trunk/src/Turtle2/includes/', ...
           ' -I/home/robocup/svn/trunk/src/Turtle2/Libs', ...
           ' -lgeneral_robocup_functions -L/home/robocup/svn/trunk/src/Turtle2/GeneralRobocupFunctions', ...
           ' -I/home/robocup/svn/trunk/src/Turtle2/Strategy/src -I/usr/include/libxml2', ...
           ' -lgeneral_functions', ...
           ' -I/home/robocup/svn/trunk/src/Turtle2/Strategy/src/STP/strategy_learner/src', ...
           ' -I/home/robocup/svn/trunk/src/Turtle2/Strategy/src/STP/strategy_learner/inference/src/shm'
           ];



end
